package com.example.tiltmidi;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.Context;
import android.os.*;
import java.util.*;

final class BleMidi {
 static final UUID SERVICE=UUID.fromString("03B80E5A-EDE8-4B33-A751-6CE34EC4C700"), CHAR=UUID.fromString("7772E5DB-3868-4112-A1A9-F2669D106BF3"), CCC=UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");
 interface Listener{void status(String s);}
 private final Context ctx; private final Listener listener; private BluetoothGattServer server; private BluetoothLeAdvertiser advertiser; private BluetoothGattCharacteristic characteristic; private final Set<BluetoothDevice> subscribed=Collections.synchronizedSet(new HashSet<>());
 BleMidi(Context c,Listener l){ctx=c;listener=l;}
 private final AdvertiseCallback adv=new AdvertiseCallback(){public void onStartSuccess(AdvertiseSettings s){listener.status("BLE 广播中，请在接收端 MIDI 设置中连接");}public void onStartFailure(int e){listener.status("BLE 广播失败："+e);}};
 boolean start(){try{BluetoothManager manager=(BluetoothManager)ctx.getSystemService(Context.BLUETOOTH_SERVICE);BluetoothAdapter a=manager.getAdapter();if(a==null||!a.isEnabled()){listener.status("请先打开蓝牙");return false;}advertiser=a.getBluetoothLeAdvertiser();if(advertiser==null){listener.status("手机不支持 BLE 外设广播");return false;}server=manager.openGattServer(ctx,callback);if(server==null)throw new IllegalStateException("无法打开 GATT 服务");BluetoothGattService s=new BluetoothGattService(SERVICE,BluetoothGattService.SERVICE_TYPE_PRIMARY);characteristic=new BluetoothGattCharacteristic(CHAR,BluetoothGattCharacteristic.PROPERTY_READ|BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE|BluetoothGattCharacteristic.PROPERTY_NOTIFY,BluetoothGattCharacteristic.PERMISSION_READ|BluetoothGattCharacteristic.PERMISSION_WRITE);characteristic.addDescriptor(new BluetoothGattDescriptor(CCC,BluetoothGattDescriptor.PERMISSION_READ|BluetoothGattDescriptor.PERMISSION_WRITE));s.addCharacteristic(characteristic);if(!server.addService(s))throw new IllegalStateException("添加服务失败");return true;}catch(Exception e){listener.status(e.toString());stop();return false;}}
 private final BluetoothGattServerCallback callback=new BluetoothGattServerCallback(){
  public void onServiceAdded(int status,BluetoothGattService s){if(status!=BluetoothGatt.GATT_SUCCESS){listener.status("GATT 服务添加失败："+status);return;}try{advertiser.startAdvertising(new AdvertiseSettings.Builder().setAdvertiseMode(AdvertiseSettings.ADVERTISE_MODE_LOW_LATENCY).setConnectable(true).setTimeout(0).build(),new AdvertiseData.Builder().addServiceUuid(new ParcelUuid(SERVICE)).build(),new AdvertiseData.Builder().setIncludeDeviceName(true).build(),adv);}catch(Exception e){listener.status(e.toString());}}
  public void onConnectionStateChange(BluetoothDevice d,int status,int state){if(state==BluetoothProfile.STATE_CONNECTED)listener.status("接收端已连接，等待订阅 MIDI");else{subscribed.remove(d);listener.status("接收端已断开；继续广播");}}
  public void onDescriptorWriteRequest(BluetoothDevice d,int id,BluetoothGattDescriptor desc,boolean prepared,boolean response,int offset,byte[] v){boolean ok=CCC.equals(desc.getUuid())&&!prepared&&offset==0&&v.length==2;if(ok){if(Arrays.equals(v,BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE)){subscribed.add(d);listener.status("MIDI 已订阅，可以发送参数");}else if(Arrays.equals(v,BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE))subscribed.remove(d);else ok=false;}if(response)server.sendResponse(d,id,ok?BluetoothGatt.GATT_SUCCESS:BluetoothGatt.GATT_REQUEST_NOT_SUPPORTED,offset,null);}
  public void onDescriptorReadRequest(BluetoothDevice d,int id,int offset,BluetoothGattDescriptor desc){byte[] v=subscribed.contains(d)?BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE:BluetoothGattDescriptor.DISABLE_NOTIFICATION_VALUE;server.sendResponse(d,id,offset==0?BluetoothGatt.GATT_SUCCESS:BluetoothGatt.GATT_INVALID_OFFSET,offset,offset==0?v:null);}
  public void onCharacteristicReadRequest(BluetoothDevice d,int id,int offset,BluetoothGattCharacteristic c){server.sendResponse(d,id,offset==0?BluetoothGatt.GATT_SUCCESS:BluetoothGatt.GATT_INVALID_OFFSET,offset,new byte[0]);}
  public void onCharacteristicWriteRequest(BluetoothDevice d,int id,BluetoothGattCharacteristic c,boolean prepared,boolean response,int offset,byte[] v){if(response)server.sendResponse(d,id,prepared?BluetoothGatt.GATT_REQUEST_NOT_SUPPORTED:BluetoothGatt.GATT_SUCCESS,offset,null);}
 };
 boolean connected(){return !subscribed.isEmpty();}
 boolean send(int channel,int cc,int value){if(server==null||subscribed.isEmpty())return false;int t=(int)(SystemClock.elapsedRealtime()&8191);byte[] packet={(byte)(128|((t>>7)&63)),(byte)(128|(t&127)),(byte)(176|(channel-1)),(byte)cc,(byte)value};boolean ok=true;try{BluetoothDevice[] peers; synchronized(subscribed){peers=subscribed.toArray(new BluetoothDevice[0]);}for(BluetoothDevice d:peers){if(Build.VERSION.SDK_INT>=33)ok&=server.notifyCharacteristicChanged(d,characteristic,false,packet)==BluetoothStatusCodes.SUCCESS;else{characteristic.setValue(packet);ok&=server.notifyCharacteristicChanged(d,characteristic,false);}}}catch(Exception e){listener.status("发送失败："+e.getMessage());return false;}return ok;}
 void stop(){try{if(advertiser!=null)advertiser.stopAdvertising(adv);if(server!=null)server.close();}catch(Exception ignored){}server=null;advertiser=null;subscribed.clear();}
}
