package com.example.tiltmidi;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.hardware.*;import android.os.*;import android.view.*;import android.widget.*;import android.text.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity implements SensorEventListener {
 SensorManager sensors; Sensor rotation; BleMidi ble; RtpMidi rtp; ArrayList<Mapping> maps=new ArrayList<>(); LinearLayout root,cards; TextView status,angle; float pitch,roll,zeroPitch,zeroRoll; SharedPreferences prefs; Handler clock=new Handler(); boolean active=false; int turn=0,sent=0;
 final Runnable tick=new Runnable(){public void run(){if(!active)return; angle.setText(String.format(java.util.Locale.US,"Pitch %.1f° · Roll %.1f° · 已发送 %d",pitch-zeroPitch,roll-zeroRoll,sent));if((ble.connected()||rtp.connected())&&!maps.isEmpty()){for(int n=0;n<maps.size();n++){Mapping m=maps.get(turn++%maps.size());if(!m.enabled)continue;int v=m.value(m.axis==1?pitch-zeroPitch:roll-zeroRoll);if(v!=m.last){if((rtp.connected()?rtp.send(m.channel,m.cc,v):ble.send(m.channel,m.cc,v))){m.last=v;sent++;}break;}}}clock.postDelayed(this,10);}};
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("config",0);load();sensors=(SensorManager)getSystemService(SENSOR_SERVICE);rotation=sensors.getDefaultSensor(Sensor.TYPE_GAME_ROTATION_VECTOR);if(rotation==null)rotation=sensors.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);build();ble=new BleMidi(this,s->runOnUiThread(()->{status.setText(s);for(Mapping m:maps)m.last=-1;}));rtp=new RtpMidi(s->runOnUiThread(()->{status.setText(s);for(Mapping m:maps)m.last=-1;}));}
 void start(){if(Build.VERSION.SDK_INT>=31&&(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.BLUETOOTH_ADVERTISE)!=PackageManager.PERMISSION_GRANTED)){requestPermissions(new String[]{Manifest.permission.BLUETOOTH_CONNECT,Manifest.permission.BLUETOOTH_ADVERTISE},9);return;}rtp.disconnect();ble.stop();ble.start();}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==9&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)start();else status.setText("请授予蓝牙连接和广播权限");}
 void build(){getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);ScrollView sc=new ScrollView(this);root=column();root.setPadding(24,24,24,32);sc.addView(root);setContentView(sc);root.addView(text("Tilt MIDI · 体感控制器",24));status=text("未启动 BLE MIDI",14);root.addView(status);angle=text("等待传感器",16);root.addView(angle);root.addView(btn("启动 / 重启 BLE MIDI",()->start()));root.addView(btn("停止 MIDI",()->{ble.stop();rtp.disconnect();status.setText("已停止");}));root.addView(btn("连接 RTP-MIDI（Wi-Fi）",()->rtpDialog()));root.addView(btn("当前位置校准为中心",()->{zeroPitch=pitch;zeroRoll=roll;for(Mapping m:maps)m.filtered=Double.NaN;}));root.addView(btn("添加控制器",()->{if(maps.size()>=32){status.setText("最多 32 个映射");return;}maps.add(new Mapping());save();render();}));cards=column();root.addView(cards);root.addView(text("Wi-Fi RTP-MIDI：输入 Mac 网络会话或 Windows rtpMIDI 主机 IP 与 UDP 控制端口（通常 5004）。BLE 或 RTP-MIDI 二选一。保持前台运行。",13));render();}
 LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setPadding(0,8,0,8);return t;}
 Button btn(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setOnClickListener(v->r.run());return b;}
 void render(){cards.removeAllViews();for(Mapping m:maps){LinearLayout box=column();box.setPadding(8,20,8,20);box.addView(field("名称",m.name,s->{m.name=s;save();},false));Spinner axis=new Spinner(this);axis.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"左右倾斜 Roll","前后倾斜 Pitch","手动滑块"}));axis.setSelection(m.axis);axis.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>a){}public void onItemSelected(AdapterView<?>a,View v,int i,long id){m.axis=i;m.filtered=Double.NaN;m.last=-1;save();}});box.addView(axis);number(box,"CC 编号 (0–127)",m.cc,0,127,v->m.cc=v);number(box,"MIDI 通道 (1–16)",m.channel,1,16,v->m.channel=v);number(box,"输出最小值 (0–127)",m.low,0,127,v->m.low=v);number(box,"输出最大值 (0–127)",m.high,0,127,v->m.high=v);number(box,"单侧倾斜角度 (5–180°)",(int)m.range,5,180,v->m.range=v);number(box,"平滑响应 (1–100%，高=响应更快)",(int)(m.smooth*100),1,100,v->m.smooth=v/100.0);CheckBox enabled=new CheckBox(this);enabled.setText("启用此参数");enabled.setChecked(m.enabled);enabled.setOnCheckedChangeListener((v,b)->{m.enabled=b;m.last=-1;save();});box.addView(enabled);CheckBox reverse=new CheckBox(this);reverse.setText("反向");reverse.setChecked(m.invert);reverse.setOnCheckedChangeListener((v,b)->{m.invert=b;m.filtered=Double.NaN;save();});box.addView(reverse);TextView label=text("手动值："+m.manual,14);box.addView(label);SeekBar manual=new SeekBar(this);manual.setMax(127);manual.setProgress(m.manual);manual.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){save();}public void onProgressChanged(SeekBar b,int p,boolean user){m.manual=p;label.setText("手动值："+p);}});box.addView(manual);box.addView(btn("删除此控制器",()->{maps.remove(m);save();render();}));cards.addView(box);}}
 EditText field(String label,String initial,java.util.function.Consumer<String> setter,boolean numeric){EditText e=new EditText(this);e.setSingleLine();if(numeric)e.setInputType(2);e.setText(initial);e.setHint(label);e.setContentDescription(label);e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){setter.accept(s.toString());}public void afterTextChanged(Editable e){}});return e;}
 void number(LinearLayout box,String label,int initial,int lo,int hi,java.util.function.IntConsumer setter){box.addView(text(label,12));box.addView(field(label,""+initial,s->{try{int v=Integer.parseInt(s);if(v<lo||v>hi)return;setter.accept(v);for(Mapping m:maps){m.last=-1;m.filtered=Double.NaN;}save();}catch(NumberFormatException ignored){}},true));}
 void save(){try{JSONArray a=new JSONArray();for(Mapping m:maps)a.put(m.json());prefs.edit().putString("maps",a.toString()).apply();}catch(Exception e){status.setText("保存失败："+e.getMessage());}}
 void load(){try{String raw=prefs.getString("maps",null);if(raw==null){maps.add(new Mapping());return;}JSONArray a=new JSONArray(raw);for(int i=0;i<Math.min(32,a.length());i++)maps.add(Mapping.parse(a.getJSONObject(i)));}catch(Exception e){maps.add(new Mapping());}}
 @Override public void onResume(){super.onResume();active=true;if(rotation!=null)sensors.registerListener(this,rotation,10000);else status.setText("无姿态传感器，请用手动滑块");clock.post(tick);}
 @Override public void onPause(){active=false;clock.removeCallbacks(tick);sensors.unregisterListener(this);if(ble!=null)ble.stop();if(rtp!=null)rtp.disconnect();save();super.onPause();}
 @Override public void onSensorChanged(SensorEvent e){float[]r=new float[9],o=new float[3];SensorManager.getRotationMatrixFromVector(r,e.values);SensorManager.getOrientation(r,o);pitch=(float)Math.toDegrees(o[1]);roll=(float)Math.toDegrees(o[2]);}
 @Override public void onAccuracyChanged(Sensor s,int a){}
 @Override public void onDestroy(){if(ble!=null)ble.stop();if(rtp!=null)rtp.disconnect();super.onDestroy();}
 void rtpDialog(){LinearLayout x=column();x.setPadding(40,10,40,0);EditText host=new EditText(this);host.setHint("电脑 IP，例如 192.168.1.20");host.setSingleLine();x.addView(host);EditText port=new EditText(this);port.setHint("AppleMIDI 控制端口，默认 5004");port.setText("5004");port.setInputType(2);port.setSingleLine();x.addView(port);new AlertDialog.Builder(this).setTitle("连接 Wi-Fi RTP-MIDI").setMessage("Windows 安装 rtpMIDI 后创建会话；macOS 在音频 MIDI 设置中开启 Network Session。输入电脑局域网 IP 和控制端口。通常数据端口为控制端口+1。").setView(x).setNegativeButton("取消",null).setPositiveButton("连接",(d,w)->{try{ble.stop();if(!rtp.connect(host.getText().toString(),Integer.parseInt(port.getText().toString())))status.setText("RTP-MIDI 连接失败");else status.setText("RTP-MIDI 正在握手…");}catch(Exception e){status.setText("请填写有效 IP 和端口");}}).show();}
}
