package com.example.tiltmidi;
import android.os.SystemClock;import java.net.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.atomic.AtomicBoolean;
final class RtpMidi{
 interface Listener{void status(String s);} final Listener l; final AtomicBoolean run=new AtomicBoolean(); DatagramSocket ctl,data; InetAddress peer; int port,ssrc,seq; volatile boolean ready;
 RtpMidi(Listener x){l=x;} boolean connected(){return ready;}
 synchronized boolean connect(String host,int p){disconnect();try{peer=InetAddress.getByName(host.trim());port=p;ctl=new DatagramSocket();data=new DatagramSocket();ctl.setSoTimeout(500);data.setSoTimeout(700);ssrc=new Random().nextInt();seq=new Random().nextInt(65536);run.set(true);new Thread(this::handshake,"rtp-midi").start();return true;}catch(Exception e){l.status("RTP-MIDI: "+e);disconnect();return false;}}
 void handshake(){try{int token=new Random().nextInt();byte[] q=ctrl("IN",token,ssrc,"Tilt MIDI");if(!invite(ctl,port,q,token)){l.status("RTP-MIDI 握手超时，请检查电脑 IP/端口和防火墙");disconnect();return;}ready=true;l.status("RTP-MIDI 已连接 UDP "+port+"/"+(port+1));receive();}catch(Exception e){if(run.get())l.status("RTP-MIDI: "+e);disconnect();}}
 boolean invite(DatagramSocket s,int p,byte[] q,int token)throws Exception{byte[] b=new byte[2048];long end=SystemClock.elapsedRealtime()+7000;while(run.get()&&SystemClock.elapsedRealtime()<end){s.send(new DatagramPacket(q,q.length,peer,p));try{DatagramPacket x=new DatagramPacket(b,b.length);s.receive(x);if(x.getAddress().equals(peer)&&x.getLength()>=16&&cmd(b,"OK")&&u32(b,4)==Integer.toUnsignedLong(token))return true;}catch(SocketTimeoutException e){}}return false;}
 static byte[] ctrl(String c,int token,int src,String n){byte[] z=n.getBytes(StandardCharsets.UTF_8);ByteBuffer b=ByteBuffer.allocate(16+z.length).order(ByteOrder.BIG_ENDIAN);b.putShort((short)0xffff).put(c.getBytes(StandardCharsets.US_ASCII)).putShort((short)2).putInt(token).putInt(src).put(z);return b.array();}
 static boolean cmd(byte[]b,String c){return b[0]==-1&&b[1]==-1&&b[2]==c.charAt(0)&&b[3]==c.charAt(1);}static long u32(byte[]b,int p){return Integer.toUnsignedLong(ByteBuffer.wrap(b,p,4).getInt());}
 synchronized boolean send(int ch,int cc,int v){if(!ready)return false;try{ByteBuffer b=ByteBuffer.allocate(20).order(ByteOrder.BIG_ENDIAN);b.put((byte)0x80).put((byte)0x61).putShort((short)seq++).putInt((int)((SystemClock.elapsedRealtime()*10)&0xffffffffL)).putInt(ssrc);b.put((byte)3).put((byte)(0xb0|((ch-1)&15))).put((byte)(cc&127)).put((byte)(v&127));byte[]x=new byte[b.position()];b.flip();b.get(x);data.send(new DatagramPacket(x,x.length,peer,port+1));return true;}catch(Exception e){l.status("RTP-MIDI发送失败");return false;}}
 void receive(){byte[]b=new byte[2048];while(run.get())try{DatagramPacket p=new DatagramPacket(b,b.length);data.receive(p);}catch(SocketTimeoutException e){}catch(Exception e){break;}}
 synchronized void disconnect(){ready=false;run.set(false);if(ctl!=null)ctl.close();if(data!=null)data.close();ctl=null;data=null;}
}
